if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Executable not found: ${INPUT}")
endif()
if(NOT DEFINED MINIMUM_SIZE)
    set(MINIMUM_SIZE 1400000)
endif()
file(SIZE "${INPUT}" CURRENT_SIZE)
if(CURRENT_SIZE LESS MINIMUM_SIZE)
    math(EXPR REMAINING "${MINIMUM_SIZE} - ${CURRENT_SIZE}")
    string(REPEAT "0123456789ABCDEF" 4096 CHUNK)
    string(LENGTH "${CHUNK}" CHUNK_SIZE)
    while(REMAINING GREATER 0)
        if(REMAINING LESS CHUNK_SIZE)
            string(SUBSTRING "${CHUNK}" 0 ${REMAINING} PART)
            file(APPEND "${INPUT}" "${PART}")
            set(REMAINING 0)
        else()
            file(APPEND "${INPUT}" "${CHUNK}")
            math(EXPR REMAINING "${REMAINING} - ${CHUNK_SIZE}")
        endif()
    endwhile()
endif()
